{% set name = "ploomber-core" %}
{% set version = "0.2.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ploomber-core-{{ version }}.tar.gz
  sha256: 6ba97a39f6dc20053ffa2f9d7f9885ced72b6632f4b7dae45d24b718b63f6292

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click
    - posthog
    - python >=3.6
    - pyyaml

test:
  imports:
    - ploomber_core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/ploomber-core/
  dev_url: https://github.com/ploomber/core
  summary: Core module shared across Ploomber projects.
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - edublancas
